version: '3.8'

services:
  app:
    restart: on-failure
    build:
      context: ./app/
    command: bash docker-entrypoint.test.sh
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./cutout_cdn:/cutout_cdn
    env_file:
      - ./env/.env.dev
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./env/.env.dev
    volumes:
      - ./data/test_database/:/var/lib/mysql/
    ports:
      - "3306:3306"