version: '3.8'

services:
  app:
    restart: always
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.app.sh
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_ouput
    env_file:
      - ../env/.env.dev
  celery:
    restart: always
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.celery.sh
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_ouput
    depends_on:
      - app
      - rabbitmq
    env_file:
      - ../env/.env.dev
  rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
      - "5672:5672"
    env_file:
      - ../env/.env.dev
  celery_beat:
    restart: always
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.celery_beat.sh
    volumes:
      - ../app:/app
    depends_on:
      - app
      - rabbitmq
      - celery
    env_file:
      - ../env/.env.dev
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../env/.env.dev
    volumes:
      - ../data/database/:/var/lib/mysql/
    ports:
      - "3306:3306"
  nginx:
    restart: always
    build: ../nginx
    volumes:
      - ../static:/static
      - ../data/cutout_cdn:/cutout_cdn
    ports:
      - "80:80"
    depends_on:
      - app
