version: '3.8'

services:
  app:
    restart: on-failure
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/ghost_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
  database:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=django_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    ports:
      - "3306:3306"
