version: '3.8'

services:
  app:
    restart: on-failure
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/ghost_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
    env_file:
      - ../env/.env.dev
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../env/.env.dev
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    ports:
      - "3306:3306"
    platform: linux/x86_64
