version: '3.8'

services:
  celery:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.celery.sh
    env_file:
      - ../env/.env.dev
  celery_beat:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.celery_beat.sh
    env_file:
      - ../env/.env.dev
  rabbitmq:
    restart: always
    image: rabbitmq:3.10.6-management-alpine
    ports:
      - 5672:${MESSAGE_BROKER_PORT}
      - 15672:${MESSAGE_BROKER_MANAGEMENT_PORT}
    volumes:
      - ../data/rabbitmq_data:/data
    env_file:
      - ../env/.env.dev
  database:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/database/:/var/lib/mysql/
    env_file:
      - ../env/.env.dev
  flower:
    build:
      context: ../flower/
    command: bash entrypoints/docker-entrypoint.flower.sh
    ports:
      - "8888:${FLOWER_PORT}"
    volumes:
      - ../app/entrypoints:/data/entrypoints
    env_file:
      - ../env/.env.dev
  app_dev:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.app.dev.sh
    ports:
      - 8000:${WEB_APP_PORT}
    env_file:
      - ../env/.env.dev
    networks:
      default:
        aliases:
          - ${WEB_APP_HOST}
