version: '3.8'

services:
  app:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.app.sh
    ports:
      - 8000:${WEB_APP_PORT}
    profiles: ["full_prod", "slim_prod"]
    env_file:
      - ../env/.env.dev
    networks:
      default:
        aliases:
          - ${WEB_APP_HOST}
  celery:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.celery.sh
    profiles: ["full_prod", "full_dev", "batch"]
    env_file:
      - ../env/.env.dev
  celery_beat:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.celery_beat.sh
    profiles: ["full_prod", "full_dev", "batch"]
    env_file:
      - ../env/.env.dev
  rabbitmq:
    restart: always
    image: rabbitmq:3.10.6-management-alpine
    ports:
      - 5672:${MESSAGE_BROKER_PORT}
      - 15672:${MESSAGE_BROKER_MANAGEMENT_PORT}
    volumes:
      - ../data/rabbitmq_data:/data
      - ../data/rabbitmq_data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - ../env/.env.dev
    profiles: ["full_prod", "full_dev", "batch"]
  database:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/database/:/var/lib/mysql/
    profiles: ["full_prod", "slim_prod", "full_dev", "slim_dev", "batch"]
    env_file:
      - ../env/.env.dev
  nginx:
    extends:
      file: docker-compose.blast_base.yml
      service: nginx_base
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    profiles: ["full_prod"]
  nginx_slim:
    extends:
      file: docker-compose.blast_base.yml
      service: nginx_base
    volumes:
      - ../nginx/default_slim.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - nginx
    profiles: ["slim_prod"]
  flower:
    build:
      context: ../flower/
    command: bash entrypoints/docker-entrypoint.flower.sh
    ports:
      - "8888:${FLOWER_PORT}"
    volumes:
      - ../app/entrypoints:/data/entrypoints
    env_file:
      - ../env/.env.dev
    profiles: ["full_prod", "full_dev", "batch"]
  app_test:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - "8000:${WEB_APP_PORT}"
    networks:
      default:
        aliases:
          - app
    env_file:
      - ../env/.env.dev
    profiles: ["test"]
  app_ci:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - 8000:${WEB_APP_PORT}
    networks:
      default:
        aliases:
          - ${WEB_APP_HOST}
    env_file:
      - ../env/.env.ci
    profiles: ["ci"]
  database_test:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    networks:
      default:
        aliases:
          - ${DATABASE_HOST}
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=blast_db"
    profiles: ["test", "ci"]
  app_dev:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.app.dev.sh
    ports:
      - 8000:${WEB_APP_PORT}
    profiles: ["full_dev", "slim_dev", "batch"]
    env_file:
      - ../env/.env.dev
    networks:
      default:
        aliases:
          - ${WEB_APP_HOST}
  docs:
    extends:
      file: docker-compose.blast_base.yml
      service: ${BLAST_IMAGE}
    command: bash entrypoints/docker-entrypoint.docs.sh
    volumes:
      - ../docs:/docs
    profiles: ["docs"]
  batch:
    image: python:3.9-buster
    volumes:
      - ../batch/run_batch.py:/run_batch.py
      - ../app/entrypoints/wait-for-it.sh:/wait-for-it.sh
      - ../batch/docker-entrypoint.batch.sh:/docker-entrypoint.batch.sh
      - ${BATCH_CSV}:/input.csv
      - ${OUTPUT_CSV}:/results.csv
    profiles: ["batch"]
    command: bash docker-entrypoint.batch.sh
    network_mode: "host"
    env_file:
      - ../env/.env.dev
