version: '3.8'

services:
  app:
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.app.sh
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/pospector_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
    env_file:
      - ../env/.env.dev
  celery:
    restart: always
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.celery.sh
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/pospector_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
    env_file:
      - ../env/.env.dev
  rabbitmq:
    restart: always
    image: rabbitmq:3.9-alpine
    ports:
      - "5672:5672"
    env_file:
      - ../env/.env.dev
  celery_beat:
    restart: always
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.celery_beat.sh
    volumes:
      - ../app:/app
    env_file:
      - ../env/.env.dev
  database:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../env/.env.dev
    volumes:
      - ../data/database/:/var/lib/mysql/
    ports:
      - "3306:3306"
  nginx:
    restart: always
    image: nginx:1.21-alpine
    volumes:
      - ../static:/static
      - ../data/cutout_cdn:/cutout_cdn
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
