version: '3.8'

services:
  database_test:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    networks:
      default:
        aliases:
          - ${DATABASE_HOST}
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=blast_db"
  app_test:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - "8000:${WEB_APP_PORT}"
    networks:
      default:
        aliases:
          - app
    env_file:
      - ../env/.env.dev