version: '3.8'

services:
  app_dev:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.app.dev.sh
    ports:
      - 8000:${WEB_APP_PORT}
    env_file:
      - ../env/.env.dev
    networks:
      default:
        aliases:
          - ${WEB_APP_HOST}
  database:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/database/:/var/lib/mysql/
    env_file:
      - ../env/.env.dev