version: '3.8'

services:
  app:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.app.sh
    ports:
      - "8000:${WEB_APP_PORT}"
    profiles: ["full", "slim"]
  celery:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.celery.sh
    profiles: ["full"]
  celery_beat:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.celery_beat.sh
    profiles: ["full"]
  rabbitmq:
    restart: always
    image: rabbitmq:3.10.6-management-alpine
    ports:
      - 5672:${MESSAGE_BROKER_PORT}
      - 15672:${MESSAGE_BROKER_MANAGEMENT_PORT}
    volumes:
      - ../data/rabbitmq_data:/data
    env_file:
      - ../env/.env.dev
    profiles: ["full"]
  database:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/database/:/var/lib/mysql/
    profiles: ["full", "slim"]
    env_file:
      - ../env/.env.dev
  nginx:
    extends:
      file: docker-compose.blast_base.yml
      service: nginx_base
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    profiles: ["full"]
  nginx_slim:
    extends:
      file: docker-compose.blast_base.yml
      service: nginx_base
    volumes:
      - ../nginx/default_slim.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - nginx
    profiles: ["slim"]
  flower:
    build:
      context: ../flower/
    command: bash entrypoints/docker-entrypoint.flower.sh
    ports:
      - "8888:${FLOWER_PORT}"
    volumes:
      - ../app/entrypoints:/data/entrypoints
    env_file:
      - ../env/.env.dev
    profiles: ["run"]
  app_test:
    extends:
      file: docker-compose.blast_base.yml
      service: blast_base
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - "8000:${WEB_APP_PORT}"
    networks:
      default:
        aliases:
          - app
    profiles: ["test"]
  database_test:
    extends:
      file: docker-compose.blast_base.yml
      service: database_base
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    networks:
      default:
        aliases:
          - database
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=blast_db"
    profiles: ["test"]
