version: '3.8'

services:
  app:
    restart: on-failure
    build:
      context: ../app/
    command: bash entrypoints/docker-entrypoint.app.test.sh
    ports:
      - 8000:${WEB_APP_PORT}
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/ghost_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
    env_file:
      - ../env/.env.dev
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=blast_db"
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    ports:
      - 3306:${DATABASE_PORT}
    platform: linux/x86_64
