version: '3.8'

services:
  blast_base:
    restart: always
    build:
      context: ../app/
    volumes:
      - ../app:/app
      - ../data/cutout_cdn:/cutout_cdn
      - ../data/ghost_output:/ghost_output
      - ../data/prospector_output:/prospector_output
      - ../data/tns_staging:/tns_staging
      - ../data/transmission:/transmission
  nginx_base:
    restart: always
    image: nginx:1.21-alpine
    volumes:
      - ../app/static:/static
      - ../data/cutout_cdn:/cutout_cdn
    env_file:
      - ../env/.env.dev
    ports:
      - "80:${WEB_SERVER_PORT}"
  database_base:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:${DATABASE_PORT}"
