version: '3.8'

services:
  app:
    restart: on-failure
    build:
      context: ../app/
    command: bash docker-entrypoint.test.sh
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../cutout_cdn:/cutout_cdn
  database:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../data/test_database/:/var/lib/mysql/
    ports:
      - "3306:3306"
