volumes:
  blast-data: {}
  django-static: {}

services:
  blast_base:
    build:
      context: ../app/
    volumes:
      - ../app:/app
      - ./dustmapsrc:/tmp/.dustmapsrc:ro
      - ./initialized:/tmp/initialized
      - blast-data:/mnt/data
      - django-static:/app/static
  nginx_base:
    restart: always
    image: nginx:1.21-alpine
    volumes:
      - django-static:/static
      - blast-data:/data
    ports:
      - 80:${WEB_SERVER_PORT}
  database_base:
    image: mariadb:10
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:${DATABASE_PORT}
  blast_latest:
    image: ghcr.io/astrophpeter/blast:latest
    volumes:
      - ../app:/app
      - ./dustmapsrc:/tmp/.dustmapsrc:ro
      - ./initialized:/tmp/initialized
      - blast-data:/mnt/data
      - django-static:/app/static
