volumes:
  blast-data: {}
  django-static: {}

services:
  blast_base:
    build:
      context: ../app/
    volumes:
      - ../app:/app
      - ./dustmapsrc:/tmp/.dustmapsrc:ro
      - ./initialized:/tmp/initialized
      - blast-data:/mnt/data
      - django-static:/app/static
      #- ../blast-data.b64b805c44cec50d1d0503e7d10349881ace7456.tar.gz:/tmp/blast-data.b64b805c44cec50d1d0503e7d10349881ace7456.tar.gz
    env_file:
      - path: ../env/.env.default
        required: true
      - path: ../env/.env.dev
        required: false
  nginx_base:
    restart: always
    image: nginx:1.21-alpine
    volumes:
      - django-static:/static
      - blast-data:/data
    ports:
      - 80:${WEB_SERVER_PORT}
    env_file:
      - path: ../env/.env.default
        required: true
      - path: ../env/.env.dev
        required: false
  database_base:
    image: mariadb:10
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:${DATABASE_PORT}
    env_file:
      - path: ../env/.env.default
        required: true
      - path: ../env/.env.dev
        required: false
  blast_latest:
    image: ghcr.io/astrophpeter/blast:latest
    env_file:
      - path: ../env/.env.default
        required: true
      - path: ../env/.env.dev
        required: false
    volumes:
      - ../app:/app
      - ./dustmapsrc:/tmp/.dustmapsrc:ro
      - ./initialized:/tmp/initialized
      - blast-data:/mnt/data
      - django-static:/app/static
