apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-beat
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-beat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-beat
    spec:
      containers:
        - args:
            - bash
            - entrypoints/docker-entrypoint.celery_beat.sh
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env--env-dev
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env--env-dev
          image: celery-beat
          name: celery_beat
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: celery-beat-claim0
      restartPolicy: Always
      volumes:
        - name: celery-beat-claim0
          persistentVolumeClaim:
            claimName: celery-beat-claim0
status: {}
