#name: Codecov

##on:
#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    env:
#      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#   steps:
#      - uses: actions/checkout@v3
#      - name: docker compose up
#        run: bash run/blast.codecov.github_actions.sh
#      - uses: actions/checkout@master
#      - uses: codecov/codecov-action@v3
#        with:
#          flags: unittests # optional
#          name: codecov-umbrella # optional
#          fail_ci_if_error: true # optional (default = false)
#          verbose: true # optional (default = false)
