name: Conda install

on:
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: s-weigand/setup-conda@v1
      - name: Display Python version
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          conda list
          python --version
