name: Conda Install test MacOS

on:
  push:
    branches: main

jobs:
  runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                conda env create -f environment.yml
                conda activate blast
                pip install -r app/requirements.txt