name: Continuous Integration

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker compose up
        run: |
          bash run/blast.run.sh ci
      - uses: codecov/codecov-action@v4
        with:
          directory: app/
