name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker compose
        run: bash run_blast_tests.github_actions.sh
