name: Continuous Integration

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker compose up
        run: |
          touch env/.env.dev
          bash run/get_fsps_files.sh
	  bash run/get_sbi_files.sh
          bash run/blast.run.sh ci
      - uses: codecov/codecov-action@v3
        with:
          directory: app/
