name: Continuous Integration

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker compose up
        run: |
          # Ensure .env.dev exists for valid Docker Compose config
          cp env/.env.dev.example env/.env.dev
          bash run/blast.run.sh ci
      - uses: codecov/codecov-action@v3
        with:
          directory: app/
