name: Continuous Integration

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker compose up
        run: |
          docker compose \
            --profile ci \
            --project-name blast \
            -f docker/docker-compose.yml \
            --env-file env/.env.default \
            --env-file env/.env.ci \
            up --build --exit-code-from app_ci

      - uses: codecov/codecov-action@v4
        with:
          directory: app/
