name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: continuous intergration
    steps:
      - uses: actions/checkout@v2
      - name: docker compose
        run: |
            echo "$MYSQL_ROOT_PASSWORD"
            bash run_blast_tests.github_actions.sh
