name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: docker compose up
        run: echo "$MYSQL_ROOT_PASSWORD"
