name: Continuous Integration

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
    tags:
      - ci-test-*
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
    tags:
      - ci-test-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: "hub.ncsa.illinois.edu"
          username: "${{ secrets.NCSA_HARBOR_BLAST_USERNAME }}"
          password: "${{ secrets.NCSA_HARBOR_BLAST_TOKEN }}"

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./app
          file: ./app/Dockerfile
          tags: hub.ncsa.illinois.edu/blast/blast:ci
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker pull hub.ncsa.illinois.edu/blast/blast:ci
          docker tag hub.ncsa.illinois.edu/blast/blast:ci blast:dev
          touch env/.env.dev
          docker compose \
            --profile ci \
            --project-name blast \
            -f docker/docker-compose.yml \
            --env-file env/.env.default \
            --env-file env/.env.ci \
            up --exit-code-from app_ci

      - uses: codecov/codecov-action@v4
        with:
          directory: app/
